version: "3.7"
services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "5555:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_USERNAME: postgres
      ADMINER_DEFAULT_PASSWORD: postgres
      POSTGRES_DB: donno

      ADMINER_DESIGN: pepa-linha

volumes:
  db_data:
